# Generated by Django 3.2.25 on 2025-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
    ]
