# Generated by Django 3.2.25 on 2025-08-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250819_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль (открытый текст)'),
        ),
    ]
