# Generated by Django 5.2.5 on 2025-08-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_messenger',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('telegram', 'Telegram'), ('viber', 'Viber')], default='email', max_length=16, null=True, verbose_name='Предпочитаемый мессенджер'),
        ),
    ]
