# Generated by Django 5.2.5 on 2025-08-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_preferred_messenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='viber_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Viber ID'),
        ),
    ]
