# Generated by Django 5.2.5 on 2025-08-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_telegram_id_customuser_viber_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_messenger',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='viber_id',
        ),
    ]
