# Generated by Django 5.2.5 on 2025-08-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_preferred_messenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_messenger',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Предпочитаемый мессенджер'),
        ),
    ]
